# Generated by Django 5.0 on 2024-01-31 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_note_noteshared"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="noteshared",
            options={"verbose_name_plural": "Notes Shared"},
        ),
    ]
